name: 'Continuous Integration'

on:
  workflow_call:

permissions:
  checks: write
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 19]
    steps:
      - name: Check out repository ✨ (non dependabot)
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v3

      - name: Check out repository 🎉 (dependabot)
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node env 📦
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'npm'

      - name: Install dependencies 🚀
        run: npm i -g npm@latest && npm ci --prefer-offline --no-audit --omit=optional

      - name: Run linter(s) 👀
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_name: github-actions[bot]
          git_email: github-actions[bot]@users.noreply.github.com
          auto_fix: false
          continue_on_error: false
          neutral_check_on_warning: true
          eslint: true
          eslint_extensions: js,ts
          prettier: true
          prettier_extensions: js,ts

      - name: Build the package 🎉
        run: npm run build
